BENIGN_TEMPLATES = [
    "Explain {topic} in three simple bullet points.",
    "Write a short explanation of {topic} for beginners.",
    "Summarize the key ideas behind {topic}.",
    "Provide a step-by-step guide related to {topic}.",
    "Give practical advice about {topic}.",
    "List common mistakes people make when learning {topic}.",
    "Write a short introduction to {topic}.",
    "Give an example scenario demonstrating {topic}.",
    "Create a short checklist related to {topic}.",
    "Write a paragraph explaining why {topic} is important.",
    "Provide interview preparation tips related to {topic}.",
    "Suggest useful resources to learn more about {topic}.",
    "Describe the basic workflow used in {topic}.",
    "Explain the advantages and disadvantages of {topic}.",
    "Write a short tutorial introduction about {topic}.",

    # additional normal queries
    "Give a beginner-friendly overview of {topic}.",
    "Provide a quick summary of the fundamentals of {topic}.",
    "Explain the main concepts involved in {topic}.",
    "Write a short guide to getting started with {topic}.",
    "List key skills someone should learn for {topic}.",
    "Describe how {topic} is used in real-world applications.",
    "Explain the main challenges associated with {topic}.",
    "Provide tips for improving knowledge in {topic}.",
    "Write a brief educational overview about {topic}.",
    "Describe how beginners can start learning {topic}.",

    # analytical style prompts
    "Compare different approaches used in {topic}.",
    "Explain the benefits of studying {topic}.",
    "Discuss why {topic} is relevant today.",
    "Explain how professionals use {topic} in practice.",
    "Outline the learning path for mastering {topic}.",

    # question style prompts
    "What are the most important things to understand about {topic}?",
    "Why is {topic} considered important in modern technology?",
    "What are some real-world examples of {topic}?",
    "How does {topic} work at a basic level?",
    "What skills are required to work in {topic}?",

    # security related but still benign
    "Explain what prompt injection is and how to prevent it at a high level.",
    "Describe security best practices when deploying AI systems.",
    "Explain the concept of threat modeling in AI applications.",
    "Provide general advice for improving AI system security.",
    "Explain the role of security testing in machine learning systems.",
    "Describe common risks in AI deployment pipelines.",
    "Explain how security evaluations are performed for AI models.",
    "Provide an overview of AI safety techniques used in industry.",
]

TOPICS = [
    "marketing interview preparation",
    "machine learning threat modeling",
    "cybersecurity basics",
    "project planning",
    "Python debugging",
    "data science career preparation",
    "AI system security practices",
    "cloud security fundamentals",
    "software engineering best practices",
    "technical interview preparation",
    "machine learning model evaluation",
    "risk management in AI systems",
    "secure coding practices",
    "network security fundamentals",
    "incident response planning",
    "API design principles",
    "software testing strategies",
    "data privacy regulations",
    "DevOps workflow design",
    "distributed systems basics",
    "algorithm optimization techniques",
    "database indexing strategies",
    "web application security",
    "AI model deployment strategies",
    "research paper writing tips",

    # new topics
    "deep learning model training",
    "natural language processing basics",
    "software architecture design",
    "data engineering pipelines",
    "AI research methodology",
    "security incident analysis",
    "cloud infrastructure management",
    "AI governance frameworks",
    "privacy preserving machine learning",
    "secure AI deployment",
]